//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVEntityProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHakkımda
    {
        public int id { get; set; }
        public string bilgiler { get; set; }
        public string egitim { get; set; }
        public string isdeneyimleri { get; set; }
    }
}
